# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.proto import grpcdatabase_pb2 as grpcdatabase__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContent = channel.unary_unary(
                '/grpcServer.Greeter/GetContent',
                request_serializer=grpcdatabase__pb2.Request.SerializeToString,
                response_deserializer=grpcdatabase__pb2.Return.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContent,
                    request_deserializer=grpcdatabase__pb2.Request.FromString,
                    response_serializer=grpcdatabase__pb2.Return.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcServer.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcServer.Greeter/GetContent',
            grpcdatabase__pb2.Request.SerializeToString,
            grpcdatabase__pb2.Return.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
